version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: monitoring_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: urlMonitorUserPass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"
  mysql-test:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3307:3306"
    volumes:
      - dbdata-test:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"
  myapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mysql-test
volumes:
  dbdata:
  dbdata-test: